---

- hosts: all
  become: true
  tasks:


  - name: install apache2 and htop package Ubuntu
    apt:
      name:
        - apache2
        - htop
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    # or you can do this:
    # when: ansible_distribution in ["Debian", "Ubuntu"]



# now matching on CentOS
  - name: install apache2 and htop package CentOS
    dnf:
      name:
        - httpd
        - htop
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
