---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
    # or you can do this:
    # when: ansible_distribution in ["Debian", "Ubuntu"]
  - name: install apache2 and htop package
    apt:
      name:
        - apache2
        - htop
      state: latest
    when: ansible_distribution == "Ubuntu"

# now matching on CentOS
  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache2 and htop package
    dnf:
      name:
        - httpd
        - htop
      state: latest
    when: ansible_distribution == "CentOS"