---

- hosts: all
  become: true
  pre_tasks:

# Install updates on all devices on the list
  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



- hosts: dns_servers
  become: true
  tasks:

# now install specific services on DNS servers list
# Match on Ubuntu
  - name: install vim and htop package Ubuntu
    tags: dns,ubuntu
    apt:
      name:
        - vim
        - htop
      state: latest
    when: ansible_distribution == "Ubuntu"
    # OR do: when: ansible_distribution in ["Debian", "Ubuntu"]

# now matching on CentOS
  - name: install vim and htop package CentOS
    tags: dns,centos
    dnf:
      name:
        - vim
        - htop
      state: latest
    when: ansible_distribution == "CentOS"
