- name: install httpd package (CentOS)
  tags: centos,httpd,apache
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start & enable package (CentOS)
  tags: centos,httpd,apache
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"

- name: install apache2 package (Ubuntu)
  tags: ubuntu,httpd,apache
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: copy html file for site
  tags: apache,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
