- name: install bind package (CentOS)
  tags: centos,bind,dns
  dnf:
    name: bind
    state: latest
  when: ansible_distribution == "CentOS"


- name: install bind9 package (Ubuntu)
  tags: ubuntu,bind,dns
  apt:
    name: bind9
    state: latest
  when: ansible_distribution == "Ubuntu"