- name: install mariadb package (CentOS)
  tags: centos,mariadb,db
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"


- name: install mariadb package (Ubuntu)
  tags: ubuntu,mariadb,db
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"


